import jsPDF from "jspdf";
import { normalizeUploadedDocuments } from "./documentUtils.js";

export function generateVisaPDF(
  caseData,
  analysis,
  uploadedDocuments
) {
  const normalizedDocuments = normalizeUploadedDocuments(uploadedDocuments);
  const doc = new jsPDF();

  const primaryBlue = [30, 64, 175];
  const darkText = [31, 41, 55];
  const lightGray = [229, 231, 235];

  let y = 20;

  // =====================
  // HEADER
  // =====================

  doc.setFillColor(...primaryBlue);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);

  doc.setFontSize(22);
  doc.text("BlueprintAI", 105, 13, {
    align: "center",
  });

  doc.setFontSize(11);
  doc.text(
    "Visa Application Summary",
    105,
    21,
    {
      align: "center",
    }
  );

  y = 45;

  // =====================
  // CASE INFORMATION
  // =====================

  doc.setTextColor(...darkText);

  doc.setFontSize(15);
  doc.text(
    "CASE INFORMATION",
    15,
    y
  );

  y += 5;

  doc.setDrawColor(...lightGray);
  doc.line(15, y, 195, y);

  y += 10;

  doc.setFontSize(11);

  doc.text(
    `Case ID`,
    15,
    y
  );

  doc.text(
    caseData.caseId || "N/A",
    70,
    y
  );

  y += 10;

  doc.text(
    `Visa Type`,
    15,
    y
  );

  doc.text(
    caseData.visaType || "N/A",
    70,
    y
  );

  y += 10;

  doc.text(
    `Destination Country`,
    15,
    y
  );

  doc.text(
    caseData.country || "N/A",
    70,
    y
  );

  y += 10;

  doc.text(
    `Generated On`,
    15,
    y
  );

  doc.text(
    new Date().toLocaleDateString(),
    70,
    y
  );

  y += 20;

  // =====================
  // APPLICANT INFORMATION
  // =====================

  doc.setFontSize(15);

  doc.text(
    "APPLICANT INFORMATION",
    15,
    y
  );

  y += 5;

  doc.line(15, y, 195, y);

  y += 10;

  const passport =
    normalizedDocuments.find(
      (docItem) =>
        docItem.requiredDocument ===
          "Passport" &&
        docItem.passportData
    );

  doc.setFontSize(11);

  if (
    passport?.passportData
  ) {
    doc.text(
      "Name",
      15,
      y
    );

    doc.text(
      passport.passportData
        .fullName || "N/A",
      70,
      y
    );

    y += 10;

    doc.text(
      "Nationality",
      15,
      y
    );

    doc.text(
      passport.passportData
        .nationality || "N/A",
      70,
      y
    );

    y += 10;

    let expiry =
      passport.passportData
        .expiryDate || "N/A";

    try {
      expiry =
        new Date(
          expiry
        ).toLocaleDateString(
          "en-GB",
          {
            day: "2-digit",
            month: "short",
            year: "numeric",
          }
        );
    } catch {}

    doc.text(
      "Passport Expiry",
      15,
      y
    );

    doc.text(
      expiry,
      70,
      y
    );

    y += 15;
  } else {
    doc.text(
      "Applicant information unavailable",
      15,
      y
    );

    y += 15;
  }

  // =====================
  // DOCUMENT VERIFICATION
  // =====================

  doc.setFontSize(15);

  doc.text(
    "DOCUMENT VERIFICATION",
    15,
    y
  );

  y += 5;

  doc.line(15, y, 195, y);

  y += 10;

  doc.setFontSize(11);

  normalizedDocuments.forEach(
    (document) => {
      const statusText =
        document.valid
          ? "Verified"
          : "Failed";

      doc.text(
        `${document.requiredDocument}`,
        15,
        y
      );

      doc.text(
        statusText,
        120,
        y
      );

      y += 10;
    }
  );

  y += 10;

  // =====================
  // APPLICATION OVERVIEW
  // =====================

  doc.setFontSize(15);

  doc.text(
    "APPLICATION OVERVIEW",
    15,
    y
  );

  y += 5;

  doc.line(15, y, 195, y);

  y += 10;

  const overview =
    analysis?.overview ||
    "No application overview available.";

  const wrappedText =
    doc.splitTextToSize(
      overview,
      170
    );

  doc.setFontSize(11);

  doc.text(
    wrappedText,
    15,
    y
  );

  y +=
    wrappedText.length * 6 +
    20;

  // =====================
  // FOOTER
  // =====================

  doc.setDrawColor(...lightGray);

  doc.line(
    15,
    y,
    195,
    y
  );

  y += 10;

  doc.setFontSize(9);

  doc.setTextColor(
    107,
    114,
    128
  );

  doc.text(
    "Generated by BlueprintAI",
    15,
    y
  );

  doc.text(
    new Date().toLocaleString(),
    195,
    y,
    {
      align: "right",
    }
  );

  doc.save(
    `BlueprintAI_Visa_Summary_${caseData.caseId}.pdf`
  );
}